# Generated by Django 5.1.2 on 2024-10-28 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('continente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
                ('categorias', models.ManyToManyField(related_name='ofertas', to='travelOffersApp.categoria')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='travelOffersApp.pais')),
            ],
        ),
    ]
