# Generated by Django 5.1.2 on 2024-11-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelOffersApp', '0003_categoria_image_oferta_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travelOffersApp/static/img/'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travelOffersApp/static/img/'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travelOffersApp/static/img/'),
        ),
    ]
