# Generated by Django 5.1.2 on 2024-12-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelOffersApp', '0004_alter_categoria_image_alter_oferta_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('respondido', models.BooleanField(default=False)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
