# Generated by Django 5.1.2 on 2024-12-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelOffersApp', '0005_formulariocontacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariocontacto',
            name='fecha_envio',
        ),
        migrations.RemoveField(
            model_name='formulariocontacto',
            name='fecha_respuesta',
        ),
    ]
